### ISSUE TITLE
some questions about your editing results.

### ISSUE THREAD

**Issue by zhao-yiqun** [sherwinbahmani/cc3d#1]
Congratulations on the amazing results.

After reading your paper, I have some questions about how to controllable editing as  Fig.10 in your paper. For restyling,  I can understand that we can change the style latent code to achieve this. 

But for removing and Translation, Does this mean one can simply change the input 2D - layout while keep the style of other object as same before? I am not sure whether my understanding is right.  

Bests.

**Comment by sherwinbahmani** [comment]
Hi,

Yes you understood it correctly, you have to adjust the input layout and move or remove the objects while keeping the latent code. However, as noted in the paper limitations section, this does not work robustly yet. We think that adding random arrangements of the objects during training by translating and removing objects randomly could help editing work better, as the model has seen more diverse layouts during training.

Best,
Sherwin
