### ISSUE TITLE
Correctly preprocessing bedrooms ans livingrooms

### ISSUE THREAD

**Issue by yiwenchen1999** [sherwinbahmani/cc3d#12]
Hi, thank you so much for this amazing repo!

I wanted to generate your result for the livingroom. However, I noticed that all the preprocessing script in https://github.com/sherwinbahmani/threed_front_rendering/blob/main/create_dataset.sh were for bedrooms.
I followed the main idea, and changed `--dataset_filtering` and `--annotation_file` in `preprocess_data.py`, and changed `create_camera_positions.py` to `create_camera_positions_living.py`; `add_vertices_calc.py` to `add_vertices_calc.py`; and used [12,4,12] for max_coord in `normalize_dataset.py`;
The label files I got could be read by the model. I used the given livingroom checkpoint to run inference, but the results seems be worse than your paper. I wonder if any of these preprocessing steps were different from the setting you trained the model on?

Thank you again for making this work!

**Comment by sherwinbahmani** [comment]
Hi,

Can you provide example results and an example boxes.npz you processed? Do renderings with blender look correct?

**Comment by yiwenchen1999** [comment]
Hi, thank you so much for replying!
An example is here: 
[6a03badb-61ab-4e22-9564-de2fd2ed1938_LivingRoom-38434.zip](https://github.com/user-attachments/files/15938129/6a03badb-61ab-4e22-9564-de2fd2ed1938_LivingRoom-38434.zip)
rendering in blender looks fine, and layout seems consistent with bounding boxes, but it seems smaller than GT from top down.

Thank you so much for the help!

**Comment by sherwinbahmani** [comment]
Do all scenes look like this? It looks like the general labels look correct. So for some scenes and seeds the scenes might have low quality. But they should not all look like this. Generally, the quality for living rooms is lower as the complexity is higher. You should try multiple seeds for a layout input and try different boxes.npz to check for more scenes to confirm. You could also try to reproduce the FID if everything is correct on average.

**Comment by yiwenchen1999** [comment]
I tried around 30 scenes, but the quality always seem to be like this. Could it be some parameters in the preprocessing scripts were different from the training setting? 
Could you share one example boxes.npz you used to generate results so maybe I can check what is different>

Thank you again for your kind reply!

**Comment by sherwinbahmani** [comment]
Do you have the same issues with bedrooms?

Try this please, will delete the file soon, so please download and save:
https://drive.google.com/file/d/1e0_to4dG-O1zGySXc6lzh1NvbMPll7-B/view?usp=sharing

**Comment by yiwenchen1999** [comment]
Thank you so much!
The bedrooms looks good.
On a side note, I got some distortion for bedroom scenes at first, but then found line 85 of https://github.com/sherwinbahmani/threed_front_rendering/blob/main/scripts/normalize_dataset.py was commented for livingroom; switching it back solved the problem

**Comment by sherwinbahmani** [comment]
So does it look correct now for living rooms when using the files I provided?

**Comment by yiwenchen1999** [comment]
Thank you so much for following up!
The result looks a lot better with the files you shared. 
When checking what's different between these files and the files I obtained from running preprocessing, I found most aspects to be consistent, but some of the bounding boxes were slightly altered.
I suspect this be caused by 3D-Front updating some of their models at some point.

The first one below is the layout I got now, the second is the one I got from your file. Could this kind of difference cause the quality differ?
![2](https://github.com/sherwinbahmani/cc3d/assets/54717690/1552686f-6ada-4285-8ba4-bcb61774cae4)
![5](https://github.com/sherwinbahmani/cc3d/assets/54717690/78b9eafc-ee80-43b2-90fa-8b0df2dc9413)

**Comment by sherwinbahmani** [comment]
Hi,

Yes this could cause issues. I don‘t think the model is very strong towards changes in the input layouts. So it might be that the model won‘t perform the same if the input layout distribution changed. In that case it would be the best to re-train the model.

Is it confirmed somewhere that the dataset is being updated? I wonder why the authors of the dataset would change the layouts of the rooms.

**Comment by yiwenchen1999** [comment]
Thank you!
I haven't found any news updates on the dataset's website indicating the change. However, the rendered images seems to be matching the current layout boxes. I'm not sure what exactly caused this kind of mismatch between versions.

I am running your model for the comparison experiment section of a related research paper, and want to get the best result for a good evaluation experiment. I wonder if it is okay to ask for the boxes.npz input files of around 30 scenes for running this?

**Comment by sherwinbahmani** [comment]
Send me an email for that please

**Comment by yiwenchen1999** [comment]
Thank you so much! I sent an email to your toronto.edu address.
