### ISSUE TITLE
3d front rendering 

### ISSUE THREAD

**Issue by ZiAngGu1** [sherwinbahmani/cc3d#3]
Hi there 
  Thanks for the beautiful work, the result is impressive!
   I want to train my own model with 3d front dataset. Following the instructions in the dataset section, I want to preprocess the data in the wanted format, but I have no idea how to write the rendering code. 
   Could you provide the rendering code? 
   Thank you again for your contribution to the community! 
Sincerely,
ZiAng

**Comment by sherwinbahmani** [comment]
Hi,

sorry for the late reply. 

We used this script to render the images: https://github.com/DLR-RM/BlenderProc/tree/main/examples/datasets/front_3d_with_improved_mat
To create the boxes.npz in the required format we used the ATISS pre-processing code: https://github.com/nv-tlabs/atiss

Also have a look here what is required in the boxes.npz: https://github.com/sherwinbahmani/cc3d/blob/62120dd131395362f0b5d955552ab80c245f0fee/training/dataset.py#L431

The semantic_layout is specific to KITTI and not required for 3D-FRONT. The bounding box components of 3D-FRONT are created in the same format in ATISS and used to create layouts afterwards in CC3D.

**Comment by ZiAngGu1** [comment]
Thanks for the reply,
However, follow the instructions provided:
There are two main problems for me:
1. How to delete all the walls and the ceilings in 3d front in blenderproc?
2. How to set the camera projection matrix for the scene so we could make sure the camera is looking at the center of the scene 
Thank you so much for your time!
Sincerely,
ZiAng

**Comment by sherwinbahmani** [comment]
Hi,

I have pushed the rendering scripts we used into a new repo: https://github.com/sherwinbahmani/threed_front_rendering

Hopefully this will be useful!

**Comment by yotofu** [comment]
Hi, I check the [threed_front_rendering](https://github.com/sherwinbahmani/threed_front_rendering), but have no idea to generate the data, there are so many scripts in that project, could you please describe how to generate data for cc3d step by step using the threed_front_rendering repo?

**Comment by sherwinbahmani** [comment]
Hi,
the create_dataset.sh should have 4 steps to create the dataset. Have you tried that? You only have to adjust the paths to the input 3D-FRONT dataset and output directory.

**Comment by ZiAngGu1** [comment]
Thanks for the reply, @sherwinbahmani 
Use create_dataset.sh works for me. You just have to set up the environment, and remember to replace every path in the create_dataset.sh and the .sh file contains in create_dataset.sh 
@yotofu
