### ISSUE TITLE
How to get data file .zip and .npz in generate.sh ?

### ISSUE THREAD

**Issue by dengxuan08** [sherwinbahmani/cc3d#5]
Thanks for the impressive work.   
I want to test the generation with my own data, what data do I need to prepare and how do I preprocess it to get the .zip and .npz files ?  
<img width="543" alt="image" src="https://github.com/sherwinbahmani/cc3d/assets/109576283/8e301747-d7f9-4bd4-a8c0-61fa53e56133">

**Comment by sherwinbahmani** [comment]
Hi,

We used this script to render the images: https://github.com/DLR-RM/BlenderProc/tree/main/examples/datasets/front_3d_with_improved_mat
To create the boxes.npz in the required format we used the ATISS pre-processing code: https://github.com/nv-tlabs/atiss

You then just zip it with two subfolder for images and labels, having the same subsequence names as subsubfolders

**Comment by dengxuan08** [comment]
Thanks for the reply, 
I use https://github.com/sherwinbahmani/cc3d/issues/6#issuecomment-1703950163 for data preprocessing.
