### ISSUE TITLE
About rendered images in BlenderProc and boxes.npz in ATISS of 3D-FRONT bedrooms

### ISSUE THREAD

**Issue by yexin-mao** [sherwinbahmani/cc3d#6]
Hi,

Thank you for your great work.

I've followed ATISS pre-processing code to create boxes.npz. However, the boxes.npz generated by ATISS is inconsistent with the one required in dataset.py. I can see boxes["camera_coords"] and boxes["target_coords"] in KITTI preprocessing scripts (https://github.com/QhelDIV/kitti360_renderer), but have no idea how to define a camera pose distribution in 3D-FRONT, which is required in inference. The class_labels in boxes.npz is a 23-dimentional one-hot embedding instead of 16 in  supplementary.

ATISS
<img width="348" alt="Screen Shot 2023-08-27 at 19 07 20" src="https://github.com/sherwinbahmani/cc3d/assets/33065283/45e2cb63-ec26-434d-a922-4c7aaca6fe64">

dataset.py
<img width="481" alt="Screen Shot 2023-08-27 at 19 13 00" src="https://github.com/sherwinbahmani/cc3d/assets/33065283/121a2207-f1f9-49dd-bbd9-2d34f343d41b">

I also followed (https://github.com/DLR-RM/BlenderProc/tree/main/examples/datasets/front_3d_with_improved_mat) to generate the images. However, the results are a bunch of hdf5 files and the orientation is not set toward a dominant object in the scene. Did you change anything like the camera pose in their scripts? Or Did you do any post-processing?

Is it possible for you to provide a small demo dataset.zip with one scene in the format of image below that can be used directly for inference? 

<img width="432" alt="Screen Shot 2023-08-27 at 19 23 42" src="https://github.com/sherwinbahmani/cc3d/assets/33065283/eb20686f-5ba1-4691-bf76-0cdf21a9947e">

Thank you for your help in advance!

**Comment by sherwinbahmani** [comment]
Hi,

I have pushed the rendering scripts we used into a new repo: https://github.com/sherwinbahmani/threed_front_rendering

Hopefully this will be useful!

**Comment by yexin-mao** [comment]
Love it. Thank you so much.
